version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - dominikzogg
  assignees:
  - dominikzogg
  versioning-strategy: increase
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.0
    - 9.5.1
  - dependency-name: infection/infection
    versions:
    - 0.20.2
    - 0.21.0
  - dependency-name: psr7-sessions/storageless
    versions:
    - 7.2.0
